.MODEL SMALL          
.STACK 100
.DATA    
    GREETING1  DB 'INPUT 16 TIMES NUMBER 1 IN BINARY TYPE : $'  
    GREETING2  DB 'INPUT 16 TIMES NUMBER 2 IN BINARY TYPE: $' 
    RESULT    DB 'RESULT: $' 
    CFLF DB 13,10, '$'  
    NUM1 DW ?
.CODE
MAIN PROC         
    ; KHOI DONG THANH GHI DS
    MOV AX, @DATA
    MOV DS, AX      
    ; PRINT GREETING1
    MOV AH, 9
    LEA DX, GREETING1  
    INT 21H 
    ; LOOP 16 TIMES TO INPUT CHARACTER
    MOV CX,16 
    XOR BX,BX;  
    MOV AH,1 ; READ A CHARACTER FROM KEYBOARD  
    CALL LOOPINPUTCHARACTER
    MOV NUM1, BX  ;MOVE BX TO NUM1 AFTER INPUT 16 TIMES      
    CALL NEXTLINE ;NEXTLINE
    ; PRINT GREETING2
    MOV AH, 9
    LEA DX, GREETING2  
    INT 21H
    ; CONTINUE INPUT SECOND NUMBER        
    MOV CX,16
    XOR BX,BX          
    ; READ A CHARACTER FROM KEYBOARD       
    CALL LOOPINPUTCHARACTER  
    CALL NEXTLINE; NEXTLINE 
    ; PRINT RESULT GREETING
    MOV AH,9
    LEA DX,RESULT
    INT 21H
    XOR DX, DX; EMPTY DX REGISTER
    MOV DX, NUM1; MOVE VALUE OF NUMI(FIRST NUMBER) TO DX REGISTER
    ADD BX, DX; ADD BX WITH DX, RESULT IN BX
    MOV CX, 16; LOOP 16 TIMES TO PRINT 
    MOV AH,2
LOOPPRINTRESULT:
    XOR DL, DL; EMPTY DX REGISTER  
    ROL BX, 1 ; ROTATE OPERAND LEFT 1BIT AND RESTORE IN CF FLAT
    ADC DL, 30H; VALUE OF DL WILL BE 30H+CF(0/1)= 30H/31H -> 0/1(CHARACTER TYPE) 
    INT 21H 
    LOOP LOOPPRINTRESULT    
    MOV AH, 4CH
    INT 21H   
MAIN ENDP
; INPUT CHARACTER FUNTION
LOOPINPUTCHARACTER PROC
        MOV AH,1
        INT 21H 
        AND AL, 0FH; MOVE TO BIT     
        SHL BX,1; ROTATE OPERAND LEFT 1BIT
        OR BL, AL; AL -> BL
        LOOP LOOPINPUTCHARACTER
RET
LOOPINPUTCHARACTER ENDP
; NEXT LINE FUNTION
NEXTLINE PROC 
    MOV AH,9
    LEA DX,CFLF
    INT 21H  
RET
NEXTLINE ENDP
    END MAIN
