                                      .MODEL SMALL          
.STACK 100
.DATA    
    LOICHAO  DB 'NHAP CHUOI: $'  
    KETQUA DB 'KET QUA LA: $' 
    CFLF DB 13,10, '$'  
    TEMP DW ?
.CODE
MAIN PROC         
    ; KHOI DONG THANH GHI DS
    MOV AX, @DATA
    MOV DS, AX      
    ; IN LOI CHAO RA MAN HINH
    MOV AH, 9
    LEA DX, LOICHAO 
    INT 21H 
    XOR CX,CX ;CHO CX CHUA SO KI TU NHAP VAO (BAN DAU =0)
    
NHAPKYTU:
    MOV AH,1 ;NHAP CAC KY TU DEN KHI NAO ENTER
    INT 21H
    CMP AL, 13 ;SO SANH XEM CO ENTER KHONG
    JE INKETQUA ;NEU ENTER THI IN KET QUA
    PUSH AX ;CAT KY TU VUA NHAP VAO STACK
    INC CX  ; TANG CX (UNG VOI SO LUONG LY TU NHAP VAO)
    JNE NHAPKYTU ;NEU(JUMP NOT EQUAL) NHAY KHI CHUA CO ENTER
MAIN ENDP

;HAM CON "INKETQUA"
INKETQUA PROC
    ;XUONG DONG 
    MOV AH,9
    LEA DX, CFLF
    INT 21H
    ;IN CHU "KET QUA LA: "
    MOV AH,9
    LEA DX, KETQUA
    INT 21H
    HIENKETQUA: 
        POP DX ;LAY TU STACK RA (FILO)
        MOV AH,2
        INT 21H
        LOOP HIENKETQUA ;LAP THEO CX
    INKETQUA ENDP
        MOV AH, 4CH
        INT 21H      
RET
       

    END MAIN
